authenticate/urls.py
"""
Defines the URL patterns for the authenticate app

It includes routes for user login, registration, and logout, integrating
Django's built-in authentication views for logging in. The URL patterns
are configured to use custom templates and view functions for handling
these authentication processes
"""
# authenticate/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'authenticate'  # Set application namespace
urlpatterns = [
    path('login/',
         # Change default template name
         (auth_views.LoginView.
          as_view(template_name='authenticate/login.html')),
         name='login'),
    path('register/', views.register_user, name='register'),
    path('logout/', views.logout_user, name='logout'),
]

words_app/urls.py
"""
Defines the URL patterns for the words app

It includes routes for various functionalities such as viewing the
index page, managing favourite words, upgrading user accounts, viewing
specific words, generating random words, accessing games, and viewing
user profiles
"""
# words_app/urls.py

from django.urls import path
from . import views

app_name = 'words_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('favourite_words/', views.favourite_words, name='favourite'),
    path('upgrade_account/', views.upgrade_account, name='upgrade_account'),
    path('view_word/<str:word>/', views.view_word, name='view_word'),
    path('random_word/', views.random_word, name='random_word'),
    path('games/', views.view_games, name='games'),
    path('profile/', views.user_profile, name='user_profile'),
    path('view_words/<str:querystring>/', views.view_words, name='view_words'),
]

words_project/urls.py
# words_project/urls.py
from django.contrib import admin
from django.urls import path, include

# IMPORTANT: Only use 'include' to add urls for an app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('words_app.urls')),
    path('auth/', include('authenticate.urls')),
]

templates/partials/_footer.html
<!-- templates/partials/_footer.html
 convention to use underscore before the name of template -->
<footer class="border-top p-3 bg-light" id="footer">
    <div class="container">
        <div class="row">
            <div class="col-12">&copy; 
                {% now 'Y' %} Word Wizards | All Rights Reserved
            </div>
        </div>
    </div>
</footer>

templates/partials/_navbar.html
<!-- templates/partials/_navbar.html
 convention to use underscore before the name of template -->
{% load static %}

{% if user_group == 'Starter' %}
    <header class='bg-light mb-5 header-container header-starter-container' id="header">
{% elif user_group == 'Plus' %}
    <header class='bg-light mb-5 header-container header-plus-container' id="header">
{% elif user_group == 'Pro' %}
    <header class='bg-light mb-5 header-container header-pro-container' id="header">
{% else %}
    <!-- Before logging in -->
    <header class='bg-light mb-5 header-container' id="header">
{% endif %}
        <!-- Store data attributes to get access to 'static' in index.js -->
         <!-- https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes -->
        <nav 
            class="navbar navbar-expand-lg"
            id="navbar"
            data-img-logo-light="{% static 'images/word-wizards-logo-light.png' %}"
            data-img-logo-dark="{% static 'images/word-wizards-logo-dark.png' %}"
            data-light-mode-img="{% static 'images/light-mode-sun.png' %}"
            data-dark-mode-img="{% static 'images/dark-mode-moon.png' %}"
            >
            <div class="container">
                <a href="{% url 'words_app:index' %}" class="me-3 mb-4 mb-md-0">
                    <img 
                        src="{% static 'images/word-wizards-logo-light.png' %}"
                        alt="Words Wizard logo"
                        class="img-fluid"
                        id="logo">
                </a>
                <button id="theme-toggler"></button>
                {% if user.is_authenticated %}
                <!-- Show links if user is logged in -->
                    <button
                        class="navbar-toggler" 
                        type="button" 
                        data-bs-toggle="collapse"
                        data-bs-target="#div-links-container"
                        aria-controls="div-links-container"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div 
                        class="collapse navbar-collapse justify-content-end"
                        id="div-links-container">
                    {% block nav %}
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'words_app:random_word' %}">
                                    Get random word 
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'words_app:games' %}">
                                    Games
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'words_app:favourite' %}">
                                    Favourite words
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'words_app:upgrade_account' %}">
                                    Change account type?
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'words_app:user_profile' %}">
                                    Profile
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'authenticate:logout' %}">
                                    Log out
                                </a>
                            </li>
                        </ul>
                    {% endblock nav %}
                    </div>
                {% endif %}
            </div>
        </nav>
    </header>