authenticate/urls.py
"""
Defines the URL patterns for the authenticate app

It includes routes for user login, registration, and logout, integrating
Django's built-in authentication views for logging in. The URL patterns
are configured to use custom templates and view functions for handling
these authentication processes
"""
# authenticate/urls.py

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'authenticate'  # Set application namespace
urlpatterns = [
    path('login/',
         # Change default template name
         (auth_views.LoginView.
          as_view(template_name='authenticate/login.html')),
         name='login'),
    path('register/', views.register_user, name='register'),
    path('logout/', views.logout_user, name='logout'),
]

words_app/urls.py
"""
Defines the URL patterns for the words app

It includes routes for various functionalities such as viewing the
index page, managing favourite words, upgrading user accounts, viewing
specific words, generating random words, accessing games, and viewing
user profiles
"""
# words_app/urls.py

from django.urls import path
from . import views

app_name = 'words_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('favourite_words/', views.favourite_words, name='favourite'),
    path('upgrade_account/', views.upgrade_account, name='upgrade_account'),
    path('view_word/<str:word>/', views.view_word, name='view_word'),
    path('random_word/', views.random_word, name='random_word'),
    path('games/', views.view_games, name='games'),
    path('profile/', views.user_profile, name='user_profile'),
    path('view_words/<str:querystring>/', views.view_words, name='view_words'),
]

words_project/urls.py
# words_project/urls.py
from django.contrib import admin
from django.urls import path, include

# IMPORTANT: Only use 'include' to add urls for an app
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('words_app.urls')),
    path('auth/', include('authenticate.urls')),
]

authenticate/models.py
# from django.db import models

# Create your models here.

authenticate/forms.py
"""
Defines the form used for user registration

The 'RegisterForm' class encapsulates the fields required for a user to
register, including username, password, and password confirmation.
Each field is styled with Bootstrap classes for consistent UI design
"""
# authenticate/forms.py

from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    """
    Inherits from Django's Form class. It is used for user registration
    """

    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Type username here'
                }
            )
        )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Type password here'
                }
            )
        )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Type password here again'
                }
            )
        )

    def clean(self):
        """
        Overrides the default clean method in Django's 'forms.Form'
        class to add custom validation logic

        This ensures that the form becomes invalid, granting access to
        form errors, which could be displayed to the user
        """

        # Call 'forms.Form' clean method to retrieve the cleaned data
        cleaned_data = super().clean()

        # Retrieve cleaned_data information
        username = cleaned_data.get("username")
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        # Check if username already exists. Username must be unique
        if User.objects.filter(username=username).exists():
            raise ValidationError("Username already exists")

        # Check if password and confirm_password are valid
        if password and confirm_password and password != confirm_password:
            # Raise a validation error if the passwords do not match
            raise ValidationError("Passwords do not match. Try again")

        # Return the cleaned data
        return cleaned_data

authenticate/views.py
"""
Defines the view functions for user authentication operations

It includes views for user registration and logout. The registration
view handles user creation, form validation, and user authentication,
while the logout view manages user sign-out
"""
# authenticate/views.py

from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.contrib.auth.models import User, Group
from .forms import RegisterForm


def register_user(
        request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    """
    Displays a register form

    Takes in a HttpRequest and renders the register template

    Parameters
    ----------
    request: HttpRequest
        Contains metadata about the request

    Returns
    ----------
    HttpResponse | HttpResponseRedirect
    """

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']
            if password == confirm_password:
                new_user = User()
                new_user.username = form.cleaned_data['username']
                new_user.set_password(password)
                new_user.save()
                group = Group.objects.get(name='Starter')
                new_user.groups.add(group)
                login(request, new_user)
                return redirect('words_app:index')

    else:
        form = RegisterForm()

    context = {
        'form': form,
    }

    return render(request, 'authenticate/register.html', context=context)


def logout_user(request: HttpRequest) -> HttpResponseRedirect:
    """
    Logs out a user and redirects them back to login page

    Takes in a HttpRequest and returns a HttpResponseRedirect

    Parameters
    ----------
    request: HttpRequest
        Contains metadata about the request

    Returns
    ----------
    HttpResponseRedirect

    """
    logout(request)
    return redirect('authenticate:login')

authenticate/templates/authenticate/login.html
<!-- authenticate/templates/login.html
 Namespace templates: Put templates inside another directory named after
the application itself -->
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}{{ block.super }} Login{% endblock title %}

{% block content %}
<div class="container" role="region" aria-labelledby="login">
    <div class="row">
        <div class="col-md-5 mx-auto">
            <h1 id="login">Login</h1>
            {% if form.errors %}
                <p class="text-danger">
                    Your username and password didn't match. Please try again.
                </p>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <!-- Loop over each field in the form -->
                {% for field in form %}
                    <div class="form-group form-floating mt-4">
                        <!-- Add bootstap class and placeholder attribute to fields using 'widget_tweaks' -->
                        {% if field.name == 'username' %}
                            {{ field|add_class:"form-control"|attr:"placeholder:Enter username" }}
                        {% elif field.name == 'password' %}
                            {{ field|add_class:"form-control"|attr:"placeholder:Enter password" }}
                        {% endif %} 
                        <!-- Render label after so that form floating takes effect -->
                        <label for="{{ field.id_for_label }}" class="form-label">
                            {{ field.label }}
                        </label>
                    </div>
                {% endfor %}
                <div class="row d-flex justify-content-between">
                    <div class="col-sm-4 mb-3 mb-sm-0">
                        <button type="submit" class="btn btn-primary mt-4">
                            Submit
                        </button>
                    </div>
                    <div class="col-sm-6 align-content-end text-sm-end">
                        <span>Don't have an account? 
                            <a 
                                href="{% url 'authenticate:register' %}"
                                class="authenticate-links">
                                Register
                            </a>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

authenticate/templates/authenticate/register.html
<!-- authenticate/templates/register.html
 Namespace templates: Put templates inside another directory named after
the application itself -->
{% extends 'base.html' %}

{% block title %}{{ block.super }} Register{% endblock title %}

{% block content %}
<div class="container" role="region" aria-labelledby="register">
    <div class="row">
        <div class="col-md-5 mx-auto">
            <h1 id="register">Register</h1>
            <!-- Raise ValidationError if passwords do not match -->
            {% if form.errors %}
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <!-- Loop over each field in the form -->
                {% for field in form %}
                    <div class="form-group form-floating mt-4">
                        <!-- Render the field -->
                        {{ field }}
                        <!-- Render label after so that form floating takes effect -->
                        <label for="{{ field.id_for_label }}" class="form-label">
                            {{ field.label }}
                        </label>
                    </div>
                {% endfor %}
                <div class="row d-flex justify-content-between">
                    <div class="col-sm-4 mb-3 mb-sm-0">
                        <button type="submit" class="btn btn-primary mt-4">
                            Submit
                        </button>
                    </div>
                    <div class="col-sm-8 align-content-end text-sm-end">
                        <span>Have an account? 
                            <a 
                                href="{% url 'authenticate:login' %}"
                                class="authenticate-links">
                                Login
                            </a>
                        </span>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}